### ISSUE TITLE
How to run the examples

### ISSUE THREAD

**Issue by mikedoan** [0xProject/OpenZKP#383]
Congratulations on this repo!

I'm very excited and try to check out but the followings does not work for me. It does not finish and I have to stop it.
```
cargo run --example large_fib
```

**Comment by mikedoan** [comment]
Thank you for following up in twitter @Recmo - here is what i got.

```
Minhs-MacBook-Pro:OpenZKP minhdoan$ cargo run --release --example large_fib
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/examples/large_fib`
thread 'main' panicked at 'Proof failed: VerificationFailed(OodsMismatch)', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Minhs-MacBook-Pro:OpenZKP minhdoan$ RUST_BACKTRACE=1 cargo run --release --example large_fib
    Finished release [optimized] target(s) in 0.15s
     Running `target/release/examples/large_fib`
thread 'main' panicked at 'Proof failed: VerificationFailed(OodsMismatch)', src/libcore/result.rs:1084:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::continue_panic_fmt
   3: rust_begin_unwind
   4: core::panicking::panic_fmt
   5: core::result::unwrap_failed
   6: large_fib::main
   7: std::rt::lang_start::{{closure}}
   8: main
```
<img width="760" alt="Screen Shot 2019-10-15 at 4 10 34 PM" src="https://user-images.githubusercontent.com/40258599/66876364-5e576800-ef66-11e9-9698-b59de727c523.png">

**Comment by Recmo** [comment]
Than you for reporting! The `large_fib` is called 'large' because it computes a proof of substantial size. There is also a `small_fib`, which should run in about one second. It's insightful to run the examples with more verbosity:

```bash
RUST_LOG=info cargo run --release --example small_fib
```

It looks like `large_fib` has a bug in it. I will look into it.

**Comment by Recmo** [comment]
Sorry, GitHub autoclosed it because PR #384 intents to fix it and was merged into master.

@mikedoan Can you check if it is fixed now in master?

**Comment by Recmo** [comment]
`large_fib` now works for me, taking ~30 sec on 8 cores and 2GB RAM in release mode.

**Comment by mikedoan** [comment]
It's working now for me. Thanks for fixing this
